services:
  - type: web
    name: devbites
    runtime: python
    buildCommand: python -m pip install -r requirements.txt
    preDeployCommand: python -m flask bootstrap-db
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.15
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: devbites-db
          property: connectionString

databases:
  - name: devbites-db
